### ISSUE TITLE
 Problems with usage some of NTRU_ENCRYPT_PARAM_SET_ID's

### ISSUE THREAD

**Issue by squidetc** [NTRUOpenSourceProject/ntru-crypto#24]
Good day again!

during process of adding a new functionality to my application, I faced with problem of using some of NTRU_ENCRYPT_PARAM_SET_ID:
1. NTRU_EES743EP1
2. NTRU_EES401EP1
3. NTRU_EES449EP1

Firstly: I show my code, and after that - I show the way I use my methods for generate keys and encrypt-decrypt files. Some of NTRU_ENCRYPT_PARAM_SET_ID now working correctly.

I successfully do initialization(by next code with result equal 0):

uint32_t initNtruWithoutKeyDefinition()
{
	uint32_t nResult;
	nResult = ntru_crypto_drbg_instantiate(256, personalization_str, sizeof(personalization_str),
		(ENTROPY_FN) &get_entropy, &m_hDrbg);
	if(nResult != DRBG_OK) LOG_ERROR(L"ntru_crypto_drbg_instantiate returned %d", nResult);
	return nResult;
}

after that I generate key-pair, also successfully:

uint32_t GenereteNtruKeyPair(int nKeySize, 
											ENtruOptimizaion eOptim, 
											int* nSimpleBufSize, 
											uint16_t* pubKeySize,
											uint8_t** publicKey,
											uint16_t* privKeySize,
											uint8_t** privKey)
{
	NTRU_ENCRYPT_PARAM_SET_ID nTrueSet;
	uint32_t	nResult = CalculateNtruKeyParamsByTwoAxes(nKeySize, eOptim, &nTrueSet, nSimpleBufSize, pubKeySize, privKeySize);
	if(nResult != DRBG_OK) 
	{
		LOG_ERROR(L"keys size calculation executed with error %d", nResult);
		return nResult;
	}
	*publicKey = new uint8_t[*pubKeySize];
	*privKey = new uint8_t[*privKeySize];
	uint16_t expected_public_key_len = *pubKeySize;
	uint16_t expected_private_key_len = *privKeySize;

	nResult = ntru_crypto_ntru_encrypt_keygen(m_hDrbg, nTrueSet, 
		pubKeySize, *publicKey, privKeySize, *privKey);

	if(nResult != DRBG_OK) 
	{
		LOG_ERROR(L"ntru_crypto_ntru_encrypt_keygen returned %d", nResult);
		return nResult;
	}

	if(expected_public_key_len != *pubKeySize)
	{
		LOG_ERROR(L"Problem with public key len");
		return nResult;
	}

	if(expected_private_key_len != *privKeySize)
	{
		LOG_ERROR(L"Problem with public key len");
		return nResult;
	}
	return nResult;
}

And finally I do encryption and decryption file from Hard Drive, piece by piece:

uint32_t	EncryptFileNtruWithKey(CString csSourcePath,
							CString csTargetPath,
							int nSimpleBufSize,
							uint16_t pubKeySize,
							uint8_t* publicKey)
{
	//prepare paths
	USES_CONVERSION;
	char* szPathToSourceFile;
	szPathToSourceFile = T2A(csSourcePath.GetBuffer());
	csSourcePath.ReleaseBuffer();

	char* szPathToTargetFile;
	szPathToTargetFile = T2A(csTargetPath.GetBuffer());
	csTargetPath.ReleaseBuffer();

	//prepare files
	FILE *fileWithSourceData;
	do 
	{
		fileWithSourceData = fopen(szPathToSourceFile, "rb");
	} while (NULL == fileWithSourceData);

	FILE *fileWithTargetData;
	fileWithTargetData = fopen(szPathToTargetFile, "wb");

	//write to the top of file md5 from public key
	string strPubKey = string ((const char*)publicKey, pubKeySize);
	strPubKey = md5(strPubKey);
	fwrite(strPubKey.c_str(), 1, strPubKey.size(), fileWithTargetData);

	//prepare variables
	unsigned char inputBuffer[1024];
	memset(inputBuffer, 0, sizeof(inputBuffer));
	int nReadPacketSize = nSimpleBufSize;
	unsigned char encryptedBuffer[3072];
	uint16_t nEncypredBufSize = sizeof(encryptedBuffer);
	uint32_t nResult;

	//read the file until it ends
	int nBytesWereRead = fread(inputBuffer, 1, nReadPacketSize, fileWithSourceData);
	while(nBytesWereRead > 0)
	{
		nResult = ntru_crypto_ntru_encrypt(m_hDrbg, pubKeySize, publicKey,
			nBytesWereRead, inputBuffer, &nEncypredBufSize, encryptedBuffer);
		if(NTRU_OK != nResult)
		{
			LOG_ERROR(L"Problem with encryption ntru_crypto_ntru_encrypt nResult=%d", nResult);
			ATLASSERT(NULL);
			return nResult;
		}

		//write data to target file
		fwrite(&nEncypredBufSize, 1, sizeof(nEncypredBufSize), fileWithTargetData);
		fwrite(&encryptedBuffer, 1, nEncypredBufSize, fileWithTargetData);

		//read next portion of data from input file
		nBytesWereRead = fread(inputBuffer, 1, nReadPacketSize, fileWithSourceData);
	}

	fclose(fileWithSourceData);
	fclose(fileWithTargetData);

	return nResult;
}

uint32_t	DecryptFileNtruWithKey(CString csSourcePath,
								CString csTargetPath,
								uint16_t privKeySize,
								uint8_t* privateKey)
{
	USES_CONVERSION;
	char* szPathToSourceFile;
	szPathToSourceFile = T2A(csSourcePath.GetBuffer());
	csSourcePath.ReleaseBuffer();

	char* szPathToTargetFile;
	szPathToTargetFile = T2A(csTargetPath.GetBuffer());
	csTargetPath.ReleaseBuffer();

	FILE *fileWithSourceData;
	do 
	{
		fileWithSourceData = fopen(szPathToSourceFile, "rb");
	} while (NULL == fileWithSourceData);

	FILE *fileWithTargetData;
	fileWithTargetData = fopen(szPathToTargetFile, "wb");

	//////////////////////////////////////////////////////////////////////////
	unsigned char inputBuffer[3072];
	int nReadPacketSize = 0;
	unsigned char decryptedBuffer[1024];
	uint16_t nDecypredBufSize = sizeof(decryptedBuffer);
	uint32_t nResult;
	m_nDecPacketsCount = 0;

	//read md5 hash
	int nBytesWereRead = fread(inputBuffer, 1, 32, fileWithSourceData);

	//read the file until it ends
	nBytesWereRead = fread(&nReadPacketSize, 1, sizeof(nDecypredBufSize), fileWithSourceData);
	while(nBytesWereRead > 0)
	{
		//read next portion of encrypted data from input file
		nBytesWereRead = fread(inputBuffer, 1, nReadPacketSize, fileWithSourceData);
		if(nBytesWereRead != nReadPacketSize)
		{
			LOG_ERROR(L"was read from file %d bytes, instead of % bytes", nBytesWereRead, nReadPacketSize);
		}

		nDecypredBufSize = sizeof(decryptedBuffer);
		memset(decryptedBuffer, 0, sizeof(decryptedBuffer));
		//decrypt the data
		nResult = ntru_crypto_ntru_decrypt(privKeySize, privateKey, nBytesWereRead,
			inputBuffer, &nDecypredBufSize, decryptedBuffer);
		if(NTRU_OK != nResult)
		{
			LOG_ERROR(L"Problem with encryption ntru_crypto_ntru_decrypt nResult=%d", nResult);
		}

		//write decrypted data to output file
		fwrite(decryptedBuffer, 1, nDecypredBufSize, fileWithTargetData);

		//read next number of portion of encrypted data from input file
		nBytesWereRead = fread(&nReadPacketSize, 1, sizeof(nDecypredBufSize), fileWithSourceData);
		m_nDecPacketsCount++;
	}

	fclose(fileWithSourceData);
	fclose(fileWithTargetData);

	return nResult;
}

I use methods, mentioned above, in next way:
//////////////////////////////////////////
				int					nKeySize = 256;
				ENtruOptimizaion	eOptim = eX9_98_Balanced;
				int nSimpleBufSize = 0;
				uint16_t pubKeySize = 0;
				uint8_t* publicKey;
				uint16_t privKeySize = 0;
				uint8_t* privKey;
				m_clsFileCrypter.GenereteNtruKeyPair(nKeySize, eOptim, &nSimpleBufSize, &pubKeySize, &publicKey, &privKeySize, &privKey);

				m_clsFileCrypter.EncryptFileNtruWithKey(L"C:\\_CryptoTemp\\01.txt", L"C:\\_CryptoTemp\\02.ccl", nSimpleBufSize, pubKeySize, publicKey);
				m_clsFileCrypter.DecryptFileNtruWithKey(L"C:\\_CryptoTemp\\02.ccl", L"C:\\_CryptoTemp\\03.txt", privKeySize, privKey);
//////////////////////////////////////////

I enumerate all the sets, which library allows to use. 3 sets works not correct: decrypted files was not equal with source file:
Best Bandwidth with X9.98: 112 and 128 keys,
Best bandwidth and speed, no X9.98: 256 key.
NTRU_EES743EP1, NTRU_EES401EP1, NTRU_EES449EP1
https://drive.google.com/file/d/0B6FyB3lawZpbVzZvVE0wM2xVUTg/edit?usp=sharing

error appears only call DECRYPTION method from NTRU library
ntru_crypto_ntru_decrypt
result equals 12289 == 0x3001
#define NTRU_FAIL                   1

SO - final output file now can't be equal to input file...

for now - I replaced usage one sets by another, but is it possible that mentioned 3 sets will be fixed for correct NTRU library usage?

Thank you!

**Comment by jschanck-si** [comment]
I'm not able to reproduce this and we haven't heard from squidetc in a while. Closing.
