### ISSUE TITLE
vs2012/NtruBuild.sln

### ISSUE THREAD

**Issue by kaleb-himes** [NTRUOpenSourceProject/ntru-crypto#45]
'Sample_NtruEncrypt.exe' (Win32): Loaded 'C:\ntru-crypto\reference-code\C\Encrypt\vs2012\Win32\Debug\Sample_NtruEncrypt.exe'. Symbols loaded.
'Sample_NtruEncrypt.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'Sample_NtruEncrypt.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'Sample_NtruEncrypt.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'Sample_NtruEncrypt.exe' (Win32): Loaded 'C:\ntru-crypto\reference-code\C\Encrypt\vs2012\Win32\Debug\NtruEncrypt_DLL.dll'. Symbols loaded.
'Sample_NtruEncrypt.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcr120d.dll'. Cannot find or open the PDB file.
Run-Time Check Failure #2 - Stack around the variable 'encoded_public_key' was corrupted.

The program '[2396] Sample_NtruEncrypt.exe' has exited with code 0 (0x0).

**Comment by kaleb-himes** [comment]
Could not find documentation that any additional resources were needed to build. Please add documentation if sources other than the project solution are needed to build in windows.

**Comment by IDWMaster** [comment]
Unable to reproduce on my machine with VS Enterprise 2015. The issues you are experiencing may have to do with your local configuration; not a problem in the solution file.
