### ISSUE TITLE
Variable Declaration Not at Beginning of Scope

### ISSUE THREAD

**Issue by JacobBarthelmeh** [NTRUOpenSourceProject/ntru-crypto#48]
Hi,

Current versions of GCC on a Linux allows for not declaring a variable at the beginning of scope but am seeing errors being issued because of it in a Windows build with Visual Studio.

The locations are 
ntru-crypto/reference-code/C/Encrypt/src/ntru_crypto_ntru_poly.c line 297
ntru-crypto/reference-code/C/Encrypt/src/ntru_crypto_ntru_mult_coeffs_karat.c line 50
ntru-crypto/reference-code/C/Encrypt/sample/sample_NTRUEncrypt.c  line 182

Regards

**Comment by jschanck-si** [comment]
Thanks, Jacob. I pushed a branch called c89 8562b91.
Let me know if that builds and I'll put the changes in upstream.

**Comment by JacobBarthelmeh** [comment]
That allows it to compile.

I have to lower the warning level because of a "warning treated as error, no 'object' file generated" but this does not get in the way of compiling and creating a DLL/Library from the Visual Studio build. I think that warning mainly is coming from the fopen that is only in the Sample_NtruEncrypt project anyway and may possibly be attributed to settings I have locally.

Just as a side note one warning is coming up in NtruEncrypt_DLL line 403 in ntru_crypto_ntru_poly.c complaining about while(1). Though I think that is only because the static analyzer Visual Studio uses can not tell it is not an issue.

The changes solve the original issue posted about compiling with C89.
Thank you for the changes,
Jacob

**Comment by jschanck-si** [comment]
Great, thanks for the report! I've pushed the fix upstream NTRUOpenSourceProject/NTRUEncrypt@9f0a32d.
It will reach this repository the next time we do a release.

Cheers,
John
