### ISSUE TITLE
Error  in DRBG_OK (sample_NTRUEncrypt.c)

### ISSUE THREAD

**Issue by linardo** [NTRUOpenSourceProject/ntru-crypto#50]
I am trying to run the sample_NTRUEncrypt.c file.

It seems that execution exits at line 155:
`if (rc != DRBG_OK)
        /* An error occurred during DRBG instantiation. */
        return 1;
`

I am printing then the rc value and is equal to 2565. What seems to went wrong? i do not get any errors or warnings in compiling

**Comment by kpatsakis** [comment]
I believe that this is a bug that was supposed to be fixed. Change 591 to 593 in  reference-code/C/Encrypt/driver_test/__ntruEncrypt.c:    
uint8_t encoded_public_key[591];  /* sized for EES401EP2 */
Could you please check this?

**Comment by linardo** [comment]
Actually i have forked the code from https://github.com/NTRUOpenSourceProject/NTRUEncrypt and not https://github.com/NTRUOpenSourceProject/ntru-crypto. I guess they are compatible...

**Comment by linardo** [comment]
Public key in sample_NTRUEncrypt.c is `uint8_t public_key[557];` . I changed it to `uint8_t public_key[593];` but the same happens

**Comment by zhenfeizhang** [comment]
Hello,

I am sorry I wasn't able to reproduce the error from a fresh install of
https://github.com/NTRUOpenSourceProject/NTRUEncrypt

From the read of it, RC 2565 = 0A05 which is DRBG_ENTROPY_FAIL.
Can you please check the get_entropy() function to see if there were enough
entropies?
Have you changed the default seed:
seed[] = { 'U','s','e',' ','a',' ','d','i','f','f','e','r','e','n','t',' ',
's','e','e','d','!' };

Cheers,
Zhenfei

**Comment by linardo** [comment]
I haven't changed the seed, since i wanted to test code. How long the seed should be?

**Comment by zhenfeizhang** [comment]
For the default parameter set (112 bits security), the default seed (21
bytes) is long enough.
I am sorry I don't see where DRBG went wrong other than that.

Cheers,
Zhenfei

**Comment by linardo** [comment]
I changed the seed in 
`static uint8_t seed[52];
      srand(time(NULL));
      int i;
      for (i = 0; i < sizeof(seed); i++) {
          seed[i] = rand() % 256;
      }
`
Now it works!

**Comment by jschanck-si** [comment]
We changed the required seed length in NTRUOpenSourceProject/NTRUEncrypt@d16e3765 but neglected to update the sample file. I'll push a new version shortly.

Thanks!
