### ISSUE TITLE
Problems on runing the project "Sample_NtruEncrypt"

### ISSUE THREAD

**Issue by zfyseu** [NTRUOpenSourceProject/ntru-crypto#53]
Hello, everyone! I run the project "Sample_NtruEncrypt" on VS 2013.
And the compile is Ok,but when I run it,it will return directly at the following line:

 if (rc != DRBG_OK)
        /* An error occurred during DRBG instantiation. */
        return 1;

the rc is always not DRBG_OK.
Is there anyone know how to deal with the problem?
Thanks!

**Comment by zfyseu** [comment]
I have solved the problem.

for 112bits security strength, 28 bytes of seeds will be needed not 21.

 static uint8_t seed[] = {
        'U','s','e',' ','a',' ','d','i','f','f','e','r','e','n','t',' ',
		          's', 'e', 'e', 'd', '!', 'h', 'e', 'h', 'e', 'n', 'i', 'h'
    };

**Comment by jschanck-si** [comment]
This has been fixed upstream. https://github.com/NTRUOpenSourceProject/NTRUEncrypt/commit/3d36004274308feef0701bf9473e5b0775e1bf6f
